server {
    listen 80;
    index index.html;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ $uri.html =404;
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }

    location /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
